### ISSUE TITLE
Ne pas superposer à la génération

### ISSUE THREAD

**Issue by tobudim** [HermineMontrouge/P6JeuDePlateau#3]
https://github.com/HermineMontrouge/P6JeuDePlateau/blob/2ef26cf067b1a33d34491eadebf0d7e60d905e35/board.js#L119-L120

Tu devrais t'intéresser à ce que tu utilises déjà en partie, classList.
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

A la génération, il te suffirait de checker une div au hasard et regarder si elle a une classe particulière : 
- Si oui tu check une autre div au hasard
- Si non, tu peux l'utiliser pour y placer ce que tu veux.

Avec une méthode très similaire tu peux t'assurer que tu ne places pas les deux joueurs côte à côte.

Je te conseille vraiment d'oser lire la doc sur MDN et de regarder un peu les méthodes et ce qu'elles proposent : même celles que tu penses déjà bien connaître.
C'est comme ça que j'ai appris, par hasard, qu'on pouvait parcourir des objets comme des tableaux, ou que par exemple le forEach renvoyait en second argument dans son callback l'index de l'élément.

**Comment by HermineMontrouge** [comment]
Bonjour Dimitri,

Je te remercie de t'être penché sur mon travail malgré ton emploi du temps
chargé.

Je prends note de ton conseil de remplacer les boucles for par d'autres
méthodes :)

"Peut-être que toutes ces fonctions devraient faire partie de
generateBoard() ?"
J'ai séparé mes différentes méthodes sous les conseils de mon mentor,
peut-être parce que je suis débutante et qu'il préfère que je décompose
vraiment les fonctionnalités.
J'ai aussi entendu dire que c'était plus facile à maintenir puisqu'elles
sont plus indépendantes.

"A la génération, il te suffirait de checker une div au hasard et regarder
si elle a une classe particulière :

   - Si oui tu check une autre div au hasard
   - Si non, tu peux l'utiliser pour y placer ce que tu veux.

Avec une méthode très similaire tu peux t'assurer que tu ne places pas les
deux joueurs côte à côte."

Pour éviter que mes joueurs se superposent j'ai en effet ajouté une case
"empty" sur les box vides et je génère mes joueurs uniquement dans le
tableau "empty".
genaratePlayers() {
// Récupération du tableau contenant les boîtes qui ne sont pas des
asteroids
const emptyBoxes = document.querySelectorAll(".empty");

this._player1 = emptyBoxes[Math.floor(Math.random() * emptyBoxes.length)];
// On ajoute à la div la classe "player1" et on lui supprime la classe
"empty"
this._player1.classList.add("player1");
this._player1.classList.remove("empty");
console.log(this._player1); // Afiche <div class="box y-1 x-1
player1"></div>

En revanche je n'ai toujours pas trouvé de moyen pour les joueurs côte à
côte...
Je ne souhaite pas utiliser le tableau avec +1 -1 +10 -10 car ce ne sera
pas maintenable facilement si on change le nombre de cases du plateau.
J'aimerais récupérer les x et y pour dire qqchose comme ça :
// Création des 4 variables qui pointent vers case de gauche, droite, haut
et bas de player1
// Suppression de la classe "empty" sur ces cases + ajoute d'une classe
spécifique
// Player2 ne peut être généré que dans une case "empty" les deux joueurs
ne pourront pas être côte à côte
let leftBoxOfPlayer1 = player1 x - 1;
leftBoxOfPlayer1.classList.remove("empty")
leftBoxOfPlayer1.classList.add("left");
let rigthBoxOfPlayer1 = player1 x + 1;
rigthBoxOfPlayer1.classList.remove("empty")
rigthBoxOfPlayer1.classList.add("rigth");
let topBoxOfPlayer1 = player1 y - 1;
topBoxOfPlayer1.classList.remove("empty")
topBoxOfPlayer1.classList.add("top");
let bottomBoxOfPlayer1 = player1 y + 1;
bottomBoxOfPlayer1.classList.remove("empty")
bottomBoxOfPlayer1.classList.add("bottom");

Sais-tu comment je pourrais faire pour récupérer mes x et y et pouvoir agir
sur x-1 x+1 y-1 et y+1?

J'espère que ta mission avance comme tu veux :)
Merci beaucoup pour ton aide!

Bonne journée,

Hermine

___________________________________________________________________________________________________________________________________________

**Comment by tobudim** [comment]
Tu devrais utiliser Markdown ou simplement les outils de formatage de texte. ;)

> J'ai séparé mes différentes méthodes sous les conseils de mon mentor,

C'est important d'avoir des petites fonctions, où chaque action est bien séparée oui.
Cependant, si 10 fonctions sont nécessaires pour réaliser une chose, il paraît avisé de faire une fonction pour cette unique chose, et cette fonction appelle les 10 fonctions.

> En revanche je n'ai toujours pas trouvé de moyen pour les joueurs côte à côte...

Tu y es presque, là, c'est de la pure réflexion sur des connaissances que tu as déjà. En lisant la suite de la réponse, tu seras aiguillée.
Mais le plus important c'est que toi seule tu fasses le chemin de pensée et de recherches sur JavaScript. Tu le sais, c'est le plus gros du métier de développeur, c'est ça que tu dois travailler !

> Je ne souhaite pas utiliser le tableau avec +1 -1 +10 -10 car ce ne sera pas maintenable facilement si on change le nombre de cases du plateau.

Ce n'est pas vrai puisque -1 et +1 reseront identiques, et -10 et +10 serait remplacés par l'appel d'une variable qui contient le nombre de colonnes.

> Sais-tu comment je pourrais faire pour récupérer mes x et y et pouvoir agir sur x-1 x+1 y-1 et y+1?

Oui, et tu le sais déjà aussi !
Toujours, tu peux te fier aux class que tu donnes à tes div.
Après tout, c'est toi qui génère ton plateau, alors tu le génères comme tu veux non ? ;)

Et oui, c'est un autre niveau que le générateur de citation !
Mais ne t'affole pas, je te réponds comme ça rapidement mais moi aussi ça m'a coûté plusieurs jours de réflexion et de recherches.
